services:
  frontend:
    image: quiz-frontend:latest
    container_name: quiz-frontend
    ports:
      - "1314:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh

  backend:
    image: quiz-backend:latest
    container_name: quiz-backend
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped